[Interface]
Address = 0.0.0.2/32
ListenPort = 51820
PrivateKey = XXXXXXXXXXXXXXXX

PostUp = iptables -t nat -A POSTROUTING -s 172.16.0.0/24 -o eth0 -j MASQUERADE
PostUp = iptables -I INPUT -p udp -m udp --dport 51820 -j ACCEPT
PostUp = iptables -A FORWARD -i %i -j ACCEPT
PostUp = iptables -A FORWARD -o %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -s 172.16.0.0/24 -o eth0 -j MASQUERADE
PostDown = iptables -D INPUT -p udp -m udp --dport 51820 -j ACCEPT
PostDown = iptables -D FORWARD -i %i -j ACCEPT
PostDown = iptables -D FORWARD -o %i -j ACCEPT

[Peer]  #bob
PublicKey = ****
AllowedIPs = 0.0.0.1/32
PersistentKeepalive = 0

[Peer]  #charlie
PublicKey = BBBBBBBBBBBBBBBBBBBB
AllowedIPs = 0.0.0.3/32
PersistentKeepalive = 0

